<?php require 'templates/header.phtml' ?>

<h1> Libros </h1>

<table class="table">
  <thead class="table-dark">
    <th>Foto</th>
    <th>Nombre</th>
    <th>Genero</th>
    <th>Autor</th>
    <th>Editorial</th>
    <th></th>
  </thead>
  <tbody>
  <?php for ($i=0; $i < sizeof($libros); $i++): ?>
    <?php if($libros[$i]->Foto == NULL) {
        $libros[$i]->Foto  = "https://papeleriatamayo.com/img/p/es-default-home_default.jpg";
    }?>
    <tr>
    <td><img class="imgTabla" src= <?= $libros[$i]->Foto ?> alt="Foto del producto"></td>
    <td><?= $libros[$i]->Nombre ?></td>
    <td><?= $libros[$i]->Genero ?></td>
    <td><?= $libros[$i]->Autor ?></td>
    <td><?= $libros[$i]->Editorial ?></td>
    <td><a href="administration/borrarLibro/<?= $libros[$i]->ID?>">Borrar</a> <a href="administration/editarLibro/<?=$libros[$i]->ID?>" class="btn btn-warning" id="">Editar</a></td>
    </tr>
<?php endfor ?>
  </tbody>
</table>

<form action="agregarLibro" method="POST" >
  <label> Foto </label>
  <input type="text" name="Foto"/>
  <label> Nombre </label>
  <input type="text" name="Nombre"/>
  <label> Genero </label>
  <input type="text"name="Genero"/>
  <label> Autor </label>
  <select name="Autor">
  <?php for ($i=0; $i < sizeof($autores); $i++): ?>
    <option value="<?= $autores[$i]->ID?>"><?= $autores[$i]->Nombre . " " . $autores[$i]->Apellido?></option>
<?php endfor ?>
  </select>
  <label> Editorial </label>
  <input type="text"name="Editorial"/>
  <button>Agregar</button>
</form>

<h1> Autores </h1>

<table class="table">
  <thead class="table-dark">
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Edad</th>
    <th>Nacionalidad</th>
    <th>Foto</th>
    <th></th>
  </thead>
  <tbody>
  <?php for ($i=0; $i < sizeof($autores); $i++): ?>
    <?php if($autores[$i]->Foto == NULL) {
        $autores[$i]->Foto  = "https://www.elmostrador.cl/_templates/globals/img/default-avatar.jpg";
    }?>
    <tr>
    <td><img class="imgTabla" src= <?= $autores[$i]->Foto ?> alt="Foto del autor"></td>
    <td><?= $autores[$i]->Nombre ?></td>
    <td><?= $autores[$i]->Apellido ?></td>
    <td><?= $autores[$i]->Edad?></td>
    <td><?= $autores[$i]->Nacionalidad ?></td>
    <td><a href="administration/borrarAutor/<?= $autores[$i]->ID?>">Borrar</a> <a href="administration/editarAutor/<?=$autores[$i]->ID?>" class="btn btn-warning" id="">Editar</a></td>
    </tr>
<?php endfor ?>
  </tbody>
</table>

<form action="agregarAutor" method="POST" >
  <label> Foto </label>
  <input type="text" name="Foto"/>
  <label> Nombre </label>
  <input type="text" name="Nombre"/>
  <label> Apellido </label>
  <input type="text"name="Apellido"/>
  <label> Edad </label>
  <input type="number"name="Edad"/>
  <label> Nacionalidad </label>
  <input type="text"name="Nacionalidad"/>
  <button>Agregar</button>
</form>

<?php require 'templates/footer.phtml' ?>