
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MLibrary</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css\style.css">
</head>
<body>
<header>
<nav class="navbar bg-body-tertiary ">
  <div class="container-fluid">
    <a class="navbar-brand" href="libros">MyLibrary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">MyLibrary</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="libros">Libros</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="autores">Autores</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Usuario
            </a>
            <ul class="dropdown-menu">
                <?php //cuando no hay ningun administrador conectado
                if(!isset($_SESSION['Usuario'])){?>
                  <li><a class="dropdown-item" href="login">Login</a></li>
                <?php 
                }
                ?>
                
                <?php //cuando esta la session conectada
                if(isset($_SESSION['Usuario'])) {?>
                <li><a class="dropdown-item" href="logout">logout</a></li>
                <li><a class="dropdown-item" href="administration">Administration</a></li>
                <?php
                }
                ?>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav> 
</header>