<?php require 'templates/header.phtml' ?>
<ul class="list-group">
<?php $libro = $resultado[0]; ?>
<?php $autor = $resultado[1]; ?>
    <?php if($libro->Foto == NULL) {
        $libro->Foto  = "https://papeleriatamayo.com/img/p/es-default-home_default.jpg";
    }?>
    <li class="list-group-item item-task">
        <div class="card" style="width: 18rem;">
            <img src= <?= $libro->Foto ?>  class="card-img-top" alt="Foto del producto">
            <div class="card-body">
                <h5 class="card-title"><?= $libro->Nombre ?></h5> 
                <p class="card-text">Autor: <?= $autor->Nombre ?> <?= $autor->Apellido ?></p> 
                <p class="card-text">Genero: <?= $libro->Genero?></p> 
                <p class="card-text">Editorial: <?= $libro->Editorial?></p> 
            </div>
        </div>
    </li>
</ul>

<?php require 'templates/footer.phtml' ?>

